version: "3.9"

volumes:
  db-data:

services:
  mongo:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - "127.0.0.1:27017:27017"
    logging:
      driver: none

  redis:
    image: redis:6.2-alpine
    logging:
      driver: none
    ports:
      - "127.0.0.1:6379:6379"
