services:
  # Caddy is used as a reverse proxy
  caddy:
    image: "caddy:2-alpine"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./Repo:/srv/repo:ro"
      - "./Viewer:/srv/viewer:ro"
    ports:
      - "127.0.0.1:8080:80"

  # Supporting services
  openldap-search:
    image: "ghcr.io/heyitsbatman/openldap-search-server:main"
  sonic:
    image: "docker.io/valeriansaliou/sonic:latest"
    volumes:
      - "sonic_data:/var/lib/sonic/store/"
      - "./sonic-config.cfg:/etc/sonic.cfg:ro"
  mongo:
    image: "docker.io/mongo:8-noble"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "127.0.0.1:37017:27017"
    volumes:
      - "mongodb_data:/data/db"
  redis:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly:latest"
    ulimits:
      memlock: -1
    command: "--maxmemory=1gb --proactor_threads=1"
    ports:
      - "127.0.0.1:6379:6379"
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "127.0.0.1:8025:8025"
  kompressor:
    image: "ghcr.io/kompakkt/kompressor:latest"
    user: "${UID}:${GID}"
    volumes:
      - "uploads:/app/uploads"

  # Kompakkt services
  server:
    env_file: .env
    image: kompakkt/bun-base-image:latest
    user: "${UID}:${GID}"
    volumes:
      - "./Server:/kompakkt/Server"
      - "uploads:/kompakkt/Server/src/uploads"
      - "./server-config.json:/kompakkt/Server/src/config.json:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    depends_on:
      - openldap-search
      - mongo
      - redis
      - sonic
      - kompressor
      - mailhog
    ports:
      - "127.0.0.1:8123:3030"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /kompakkt/Server
    command: |
      sh -c "bun install --frozen-lockfile; bun run dev"
  repo:
    image: kompakkt/bun-base-image:latest
    depends_on:
      - server
    user: "${UID}:${GID}"
    volumes:
      - "./Repo:/kompakkt/Repo"
      - "./shared-environment.ts:/kompakkt/Repo/src/environment.ts:ro"
    working_dir: /kompakkt/Repo
    command: |
      sh -c "bun install --frozen-lockfile; bun run ng build --watch"
  viewer:
    image: kompakkt/bun-base-image:latest
    depends_on:
      - server
    user: "${UID}:${GID}"
    volumes:
      - "./Viewer:/kompakkt/Viewer"
      - "./shared-environment.ts:/kompakkt/Viewer/src/environment.ts:ro"
    working_dir: /kompakkt/Viewer
    command: |
      sh -c "bun install --frozen-lockfile; bun run ng build --watch"

volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      device: ./uploads
      o: bind
  mongodb_data: null
  sonic_data: null
